services:
  app:
    build:
      context: ./docker/php
    container_name: blog-php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      - TZ=${TZ}
    depends_on:
      - db

  web:
    image: ${NGINX_IMAGE}
    container_name: blog-nginx
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: ${POSTGRES_IMAGE}
    container_name: blog-postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"

volumes:
  pgdata:
